### ISSUE TITLE
Most up to date KiCad Library repositories

### ISSUE THREAD

**Issue by brainstorm** [freetronics/freetronics_kicad_library#4]
Hello Freetronics,

I've been using Kicad for a while now and was setting up a sensible way to manage my library effortlessly. I came across your repo and looks really nice, but then I found this one that looks much more updated, yet I still wonder if it's the best choice:

https://github.com/monostable/kicad_footprints

What is the most updated repo that the KiCad community uses as a reference nowadays?

Thanks in advance!

**Comment by projectgus** [comment]
Hi again @brainstorm  :)

Former Freetronics employee here, I'm the one who started this repo.

In 2013 when I first started this library, there weren't a lot of well-tested Kicad libraries and noone was maintaining the official libraries. Since then, the Kicad library team has done an impressive job of brining the Kicad libraries onto github and maintaining them: https://github.com/KiCad/

So, short answer, I'd recommend trying the Kicad official libraries.

When looking at other people's EDA libraries, my advice would be that the most important thing you can do is ask whether they are tested on actual PCBs and have been updated if they have errors. It's very easy to make footprints, much harder to know if they are correct! The Kicad library authors have been doing a good job of updating footprints based on reported errors.

The other thing to realise is that making PCB footprints is not impossible, it's just a bit fiddly. Don't be a afraid to make your own. :)

**Comment by brainstorm** [comment]
Thanks much @projectgus for your answer... My interest for that meta-repo of libraries was primarily to "deploy and forget" on my local installation, making sure I don't have to chase components myself and/or duplicate work by creating my own footprints only to realize that they are already created and better annotated elsewhere.

For instance, I couldn't easily find the ESP8266 nor ESP32 in the official kicad libs/footprints (browsing through the .pretty repos in kicad github org) :_(

**Comment by projectgus** [comment]
Unfortunately, in my experience doing EDA design "deploy and forget" for footprints is a pipe dream. You need to check every footprint you use (to make sure it's accurate and suitable for your own purposes), and if you don't then you inevitably end up with an expensive mistake because somone mis-annotated, or posted something they never tested themselves, or made assumptions about your fab/configuration/requirements... :|
